/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:c260d76b-8741-4d5f-b656-4371649bbdd9",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_3QtOt26Kg",
    "aws_user_pools_web_client_id": "1cho5d0hb38u2l5borluhtqpq8",
    "oauth": {}
};


export default awsmobile;
